print("additon",2+2)
print("subtraction",2-2)
print("multiplication",2*2)
print("division",2/2)
print("exponent",2**2)
print("modulus",2%2)
print("floor division",2//2)
print("complex",2+2j)
print("absolute",abs(-2))
print("round",round(2.5))
print("power",pow(2,3))